name: Deploy

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          ref: dev

      - name: Setup rust & mdbook
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Build
        run: |
          cargo install mdbook
          mdbook build

      - name: Deploy
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          REPO: git@github.com:Wortoxs/design-pattern.git
        run: |
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.email "wtox@example.com"
          git config --global user.name "wtox"
          cd ./book && git init && git add .
          git commit -m "GitHub Actions Auto Builder at $(date +'%Y-%m-%d %H:%M:%S')"
          git push --force --quiet "$REPO" master:master 